### ISSUE TITLE
Texture cannibalism

### ISSUE THREAD

**Issue by zef126** [Yuria-Shikibe/NewHorizonMod#106]
**Describe the bug**
The textures on my other mods map are disappearing!

**To Reproduce**
1. Install this mod and an other that creates a new planet
2. Try the other mod planet

**Version**
- Game Version 146
- MOD Version latest

**Expected behavior**
It don't interfere with other mods

**Crash Log**
If applicable, add log to help explain your problem. *Very Important*

**OS (please complete the following information):**
 - OS: Android

**Additional context**

**Comment by ZaharitIngot** [comment]
have same issue
