### ISSUE TITLE
Crash with t4 blue air

### ISSUE THREAD

**Issue by BlueWolf3682** [Yuria-Shikibe/NewHorizonMod#19]
While playing with the mod, I tapped on the description button for the tier 4 blue air unit (striker, I think?) and the game crashed.

OS: Android 11, Google Pixel 2
build: BE 20940
Crash Log: 
[aaaaaaaaaaaaaaaaaaaaaaaa](https://github.com/Yuria-Shikibe/NewHorizonMod/files/6218942/crash_1616986473022.txt)

**Comment by Yuria-Shikibe** [comment]
in that log I didn't find something related to this mod, so I think that's may the BE version caused the crash.
By the way I think you need update this mod too.
Sorry reply so slow because I was at school where I can't use the Internet.
