### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Xusk947** [Yuria-Shikibe/NewHorizonMod#2]
Crash when load mod, android go brr brr

```[I] Loading NewHorizon Mod Objects [E] arc.util.serialization.SerializationException: Serialization trace: {}.sector sector (mindustry.game.Rules) 	at arc.util.serialization.Json.readFields(Json.java:911) 	at arc.util.serialization.Json.readValue(Json.java:1086) 	at arc.util.serialization.Json.readValue(Json.java:987) 	at arc.util.serialization.Json.fromJson(Json.java:828) 	at mindustry.io.JsonIO.read(JsonIO.java:60) 	at mindustry.io.SaveVersion.getMeta(SaveVersion.java:42) 	at mindustry.io.SaveIO.getMeta(SaveIO.java:91) 	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:69) 	at mindustry.io.SaveIO.isSaveValid(SaveIO.java:61) 	at mindustry.game.Saves.load(Saves.java:51) 	at mindustry.core.Control.loadAsync(Control.java:230) 	at arc.assets.AssetManager$2.loadAsync(AssetManager.java:353) 	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53) 	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17) 	at arc.util.async.-$$Lambda$rdUmJAVAO4dv3DFAJBzHpUHffrw.call(Unknown Source:2) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:919) Caused by: java.lang.NullPointerException: Attempt to read from field 'arc.struct.Seq mindustry.type.Planet.sectors' on a null object reference 	at mindustry.io.JsonIO$2.read(JsonIO.java:88) 	at mindustry.io.JsonIO$2.read(JsonIO.java:78) 	at arc.util.serialization.Json.readValue(Json.java:1093) 	at arc.util.serialization.Json.readFields(Json.java:904) 	... 18 more [I] Total time to load: 12128 [I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v6.json [I] Time to generate menu: 44.717537```

**Comment by Molovtov** [comment]
That happen to me too,i know because texture of blocks make me crash

**Comment by KillerQueenZ** [comment]
No mod only pain
