### ISSUE TITLE
The game does not start.

### ISSUE THREAD

**Issue by ghost** [Yuria-Shikibe/NewHorizonMod#3]
Why Mindustry does not start with this mod? The download just freezes and restarting the game doesn't help. I deleted the all mods, same situation. Android device.

**Comment by Yuria-Shikibe** [comment]
I am sorry that this mod seems have some problem with certain type of phone when load the mod and causes stuck, which I cannot fix it because that actually is a Hardware Problem . So may be I can only cut these code off when the mod is run on a phone to save the phone players.
