### ISSUE TITLE
Void arc crash

### ISSUE THREAD

**Issue by Ginetik1** [Yuria-Shikibe/NewHorizonMod#43]
Everytime when unit\turret from mod shoots, game crashes.
[crash-report-11_03_2021_23_28_33.txt](https://github.com/Yuria-Shikibe/NewHorizonMod/files/7470527/crash-report-11_03_2021_23_28_33.txt)

**Comment by theChronodonut1337** [comment]
Yeah, I have the same problem with Collapser
[crash-report-11_04_2021_09_35_52.txt](https://github.com/Yuria-Shikibe/NewHorizonMod/files/7471722/crash-report-11_04_2021_09_35_52.txt)

**Comment by Yuria-Shikibe** [comment]
which version do you play?
I just test the mod in 134.1, but nothing wrong happened

**Comment by Ginetik1** [comment]
Same, 134.1

**Comment by theChronodonut1337** [comment]
Also 134.1

**Comment by theChronodonut1337** [comment]
It's a rare crash

**Comment by Yuria-Shikibe** [comment]
I just tried that on steam 134.1, but really nothing happen.
the NoSuchMethodError shouldn't happen since the it will directly stop the mod going through compile.

It will work fine with the new-version mod.
Anyway I am going to update the mod, just try it again after that

**Comment by Ginetik1** [comment]
Okay, thanks, gonna try again after update

**Comment by theChronodonut1337** [comment]
Oh ok

**Comment by theChronodonut1337** [comment]
Make sure the update patches the NoSuchMethod crash

**Comment by Ginetik1** [comment]
How do i update those patches?

**Comment by theChronodonut1337** [comment]
I meant that the update prevents that crash from happening in the first place

**Comment by Ginetik1** [comment]
Got it, gonna wait for the update then

**Comment by Yuria-Shikibe** [comment]
So does the latest version work well?
Or still crashing

**Comment by Ginetik1** [comment]
Same trouble, smae cras
[crash-report-11_07_2021_06_18_13.txt](https://github.com/Yuria-Shikibe/NewHorizonMod/files/7491653/crash-report-11_07_2021_06_18_13.txt)
h

**Comment by Yuria-Shikibe** [comment]
I just asked my friends and other people. They said they didn't meet that crash.
... confused

**Comment by Ginetik1** [comment]
Code is being compiled on my PC, or on yours?

**Comment by theChronodonut1337** [comment]
so anyway, is anybody gonna fix the crash involving
"NoSuchMethodError: 'void arc.struct.Seq.shuffle()'"
