### ISSUE TITLE
Lags after placing eternity turret

### ISSUE THREAD

**Issue by alpha-gamer-pro** [Yuria-Shikibe/NewHorizonMod#48]
The turret lags the game after placement,even if you exit the map the lag remains and you can see the turrets shadow which forces you to close the app and open it again to remove the lag,I dunno why this happens but it's annoying pls fix.

**Comment by Yuria-Shikibe** [comment]
I just tried fix it and reuploaded the latest release. You can install the mod and check whether this still happens.
If everything is alright , I will then close the issue

**Comment by alpha-gamer-pro** [comment]
Is it via mod browser or should I download it here on GitHub?

**Comment by alpha-gamer-pro** [comment]
It still lags

**Comment by Yuria-Shikibe** [comment]
I just reuploaded the release again, it should work now.

**Comment by alpha-gamer-pro** [comment]
Should I download it on the browser or here?

**Comment by Yuria-Shikibe** [comment]
they're the same

**Comment by alpha-gamer-pro** [comment]
It's fixed
