### ISSUE TITLE
Liquid and Item sources broken in latest public update

### ISSUE THREAD

**Issue by Lussitonic** [Yuria-Shikibe/NewHorizonMod#50]
Sources have been broken, and cannot function correctly. By that, I mean that when using them, the UI which would normally pop up is not there. 
Mod version: V1.10.9
Mindustry version: Steam Build 135
Other mods:
Developer Mode V2.3.2
RTFM V2.15.0
Scheme Size V2.2.20
Testing Utilities V28
Time Control V0.2
UI Lib V2.16.6
WAISA V2.3.3
Issue can be closed if this is due to being incompatible with any of these other mods.
Other issues noticed: 1 Map corrupted, Message Block also unable to be used.
I will further elaborate if needed.

**Comment by Yuria-Shikibe** [comment]
![image](https://user-images.githubusercontent.com/56785441/152650302-4b7b68f2-9fce-4841-acd4-83dbf3277d4b.png)
But mine just works correct.
Can you describe when these happened? Or they just bugged all the time

**Comment by Lussitonic** [comment]
It was bugged 100% of the time...
However, i was testing with a single map, so it might be a bit biased. I'll test it with my other maps.
