### ISSUE TITLE
有一个疑问，137版本的加入mod之后，战役里面看不到相应的科技树

### ISSUE THREAD

**Issue by JCven-chao** [Yuria-Shikibe/NewHorizonMod#56]
在自定义里面可以使用mod物品，但是战役里面没有相应的科技树，无法研究新物品

**Comment by Yuria-Shikibe** [comment]
新版本的MOD还没写完
我暂时还没写科技树因为方块和单位都是不完整的，所以mod目前战役用不了

**Comment by JCven-chao** [comment]
好的，实时关注着呢，如果mod加入了战役麻烦在简介提一句，万分感谢

**Comment by Yuria-Shikibe** [comment]
![image](https://user-images.githubusercontent.com/56785441/187393427-8ebdc160-f73f-4e35-b3a6-e54dbe2b8874.png)

科技树已添加
