### ISSUE TITLE
it will crashes when quad carrying a gravity-gully

### ISSUE THREAD

**Issue by zeutd** [Yuria-Shikibe/NewHorizonMod#57]
it will crashes when quad carrying a gravity-gully awa
[crash-report-09_09_2022_20_47_28.txt](https://github.com/Yuria-Shikibe/NewHorizonMod/files/9535504/crash-report-09_09_2022_20_47_28.txt)

**Comment by zeutd** [comment]
when play in server

**Comment by 18001767679** [comment]
...
又是你
（我是imcute）
