### ISSUE TITLE
Typo for surge-alloy-multifactory

### ISSUE THREAD

**Issue by xiao278** [Yuria-Shikibe/NewHorizonMod#61]
**Describe the bug**
Description says it uses Xen Alpha fluid, but actual requirements say Zeta fluid

**Screenshots**
<img width="599" alt="image" src="https://user-images.githubusercontent.com/90475159/202872882-c7be3bde-e40d-44b2-b769-8759c1920385.png">

**Comment by Yuria-Shikibe** [comment]
Now Fixed
