### ISSUE TITLE
Mod's maps doesn't work correctly. 

### ISSUE THREAD

**Issue by ShadowLeaf31** [Yuria-Shikibe/NewHorizonMod#62]
![Screenshot_20221221-132832](https://user-images.githubusercontent.com/119765073/208956063-a2cf0507-a3d5-4d06-a831-dd496d68a1ef.png)
Only 3 of the maps added by the mod can't be used or edited, like Ancient Battle, but others like Hostile HQ can't.

**Comment by ShadowLeaf31** [comment]
Sorry, *only 3 of the maps added by the mod CAN be used or edited

**Comment by Yuria-Shikibe** [comment]
I'm sorry that these map are still only valid for v135 but I just temporarily kept them, I have currently deleted them to avoid these exceptions and I will remake them in recent versions.

**Comment by ShadowLeaf31** [comment]
Ok, so thanks. I only want to play them. I hope they can update them,
because I like so much that mod and her content
