### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by TheNickname1** [Yuria-Shikibe/NewHorizonMod#63]
**To Reproduce**

just use unit transpors with mega units

**Desktop (please complete the following information):**
 - OS: android
 - Browser: in game mod browser
 - Version 0.2.2

**Smartphone (please complete the following information):**
 - Device: android
 - Version 0.2.2

[crash_1671735037711.txt](https://github.com/Yuria-Shikibe/NewHorizonMod/files/10289688/crash_1671735037711.txt)

**Comment by Yuria-Shikibe** [comment]
Fixed
