### ISSUE TITLE
Nemesis doesn't fire

### ISSUE THREAD

**Issue by kapzduke** [Yuria-Shikibe/NewHorizonMod#7]
The Nemesis turret refuses to fire. i have checked all the ammo requirements for it. not even cooling it with infinity liquid works.

**Comment by Yuria-Shikibe** [comment]
You Have to plug in a Nemesis Upgrade Build and link them. Then you can select the ammo
![QQ截图20210214093247](https://user-images.githubusercontent.com/56785441/107866064-c8a85180-6ea7-11eb-9760-a85e374d2a64.jpg)

I should make the discription more complete.

**Comment by Yuria-Shikibe** [comment]
By the way that building is in the EFFECT Category
