### ISSUE TITLE
远程仓库在核心升级后无法正常使用

### ISSUE THREAD

**Issue by phbice** [Yuria-Shikibe/NewHorizonMod#72]
重现问题的步骤：
1. 选择一个单核心区块（我的是焦油田），建立远程仓库并等待其加载完毕；
2. 将核心从次代核心升级为终代核心。

之后，远程仓库不再共享核心仓库，而是自成一个小仓库，假装它还在正常工作。虽说重建远程仓库即可解决，但还请修复这个问题，或者在远程仓库的描述里加个提示（生产基地全面崩溃的事情我不想再经历一次了）。

**Comment by Yuria-Shikibe** [comment]
已修复
