### ISSUE TITLE
unable to join friend on staem

### ISSUE THREAD

**Issue by matt-arcticfox** [Yuria-Shikibe/NewHorizonMod#78]
unable to join friend server when he has the same mod packs

**To Reproduce**
1. shift tab to open friend menu on steam
2. press join game
3. Mindustry loads world data
4. error mesage comes with
 Unknown network error cannot invoke "mindustry.net,NetConnection.close()" because "mindustry.Vars.player.com" is null
5. ok
6. confirm
Need [Setting:overide] Activated. (this disable recipes for the mod)

**Version**
- Game Version 145.1
- MOD Version 0.4.1

i expected to be able to join my friends game when he aslo has the same mods.

**Crash Log**
none

**Additional context**
none
![image_2023-07-06_115156107](https://github.com/Yuria-Shikibe/NewHorizonMod/assets/133377826/594b9e48-4ee7-4d4c-9723-779c6acd7542)
![image_2023-07-06_115214479](https://github.com/Yuria-Shikibe/NewHorizonMod/assets/133377826/7c0b4d9a-3b33-4962-8b80-f463b2436946)

**Comment by Sutherland4567** [comment]
Same kind of error but on the free versio.

**Comment by Yuria-Shikibe** [comment]
should be fixed now, try 0.4.2.1

**Comment by Sutherland4567** [comment]
thx alot im gona try
