### ISSUE TITLE
Bring back the homing lightning turret from v5

### ISSUE THREAD

**Issue by kapzduke** [Yuria-Shikibe/NewHorizonMod#8]
i remember it being so useful back in the day, but you might have to do some balancing.
![磁轨炮](https://user-images.githubusercontent.com/60543005/108065423-a6a8fd80-7066-11eb-8cf5-dd56e1ba71b1.png)

**Comment by Yuria-Shikibe** [comment]
I happen to be doing this. Though I have no idea what type of the bullet I should choose to work on the new one.
I used the PointBulletType and I found it sucks.
