### ISSUE TITLE
new striker(s)

### ISSUE THREAD

**Issue by kapzduke** [Yuria-Shikibe/NewHorizonMod#9]
t4 (original) striker
![IMG_20210219_155505](https://user-images.githubusercontent.com/60543005/108513304-13243680-72cb-11eb-9bf0-534aef973690.jpg)
t3 striker
![IMG_20210219_155524](https://user-images.githubusercontent.com/60543005/108513332-20412580-72cb-11eb-9463-e97ace7aad95.jpg)
i can send the sprites on request

**Comment by Yuria-Shikibe** [comment]
That's a good idea but I am preparing to set the striker as the T4 unit and the warper as the T3 then I am working on a new T5 air unit after the striker.

So I may won't take this, but I will take that color.
