### ISSUE TITLE
Insta crash

### ISSUE THREAD

**Issue by MoonBunn** [Yuria-Shikibe/NewHorizonMod#94]
Bug/crash happens as soon as I move on to the ancient shipyard. When you try to launch to the ship yard, it instantly crashes the game on mobile. Yet once you reload the game, it acts like you launched and used up said resources needed to launch to said shipyard. I've tried everything from restarting the game, forcing it to stop, to completely re-installing the mod, yet nothing seems to fix it no matter where you launch from.

**Comment by ArtificalHuman** [comment]
your issue may be the same as the one i have encountered, it's due to the naxos unit warping in during the start of the map, for some reason, the naxos unit currently just crashes the game when loaded in.
